baseurl = "/"
languageCode = "en-us"
title = "A Hugo website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Data Analysis"
    url = "/data_analysis/"
[[menu.main]]
    name = "R"
    url = "/R/"
[[menu.main]]
    name = "Tutorials"
    url = "/Tutorials/"
[[menu.main]]
    name = "Conferences"
    url = "/Conferences/"
[[menu.main]]
    name = "Courses"
    url = "/Courses/"

[[menu.main]]
    name = "Jobs"
    url = "/Jobs/"
[[menu.main]]
    name = "Research"
    url = "/Research/"
[[menu.main]]
    name = "Contact"
    url = "/Contact/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

